ar-io/ar-io-network-process

- spec/epochs_spec.lua
- src/epochs.lua
- src/utils.lua
This is just precaution to ensure the contract is always dealing in ms
> fix(epochs): handle unix timestsamps in ms and convert to seconds

- src/utils.lua
This is a clear indication of if there is more data to load. `totalPages` is removed as it suggests specific pages which is confusing when using cursor approach
> fix(pagination): remove totalPages and add hasMore flags to pagination

- spec/epochs_spec.lua
- src/epochs.lua
- src/gar.lua
We do all the work to compute these, but do not store them anywhere. Rather than doing more work on reads (and thus pay more gas to a CU) to compute them on the fly, we can store the weights at the beginning of an epoch and surface them in the network portal. It is important to note that weights will only change at the start of the next epoch.
> feat(gar): add gateway weights to to regsitry

- src/epochs.lua
It is resetting to 0 if they are not prescribed, instead we want a running tally
> fix(gar): fix how prescribedEpochCount is calculated

- spec/arns_spec.lua
- spec/gar_spec.lua
- spec/vaults_spec.lua
- src/arns.lua
- src/constants.lua
- src/epochs.lua
- src/gar.lua
- src/main.lua
- src/tick.lua
We can additional add the "distribute" logic to this so rewards are to be distributed at the nearest message. We will test this before we make that update.
> fix(tick): prune state on every message

- spec/gar_spec.lua
- src/gar.lua
- src/main.lua
- tests/gar.test.mjs
Because tokens are locked for a significant amount of time, we will allow delegates to cancel their withdrawls so long as they have not expired.
> feat(gar): support canceling delegate stake withdrawls 

- src/gar.lua
This will be implicitly controlled by token supply.
> fix(gar): remove limit on number of delegates for a gateway

- src/ao_event.lua
- src/main.lua
- tests/arns.test.mjs
- tests/tick.test.mjs
- Collect event info for every handler by using a wrapper function
- No longer print events in eventingPcall; expect wrapper function to handle
- Repair collection of event data for a few tables
> PE-6791: Send arrays as as arrays rather than delimited lists

- spec/epochs_spec.lua
- src/epochs.lua
Useful for validating the epoch data is correct and viewing gateways over time.
> chore(epochs): add totalEligibleGateways to epoch distribution data

- package.json
- src/main.lua
- tests/handlers.test.mjs
- tests/monitor/monitor.test.mjs
This is a hack to get around precision loss (unknown why) while we convert to big int
> chore(test): add computed supply monitoring tests

- spec/gar_spec.lua
- src/constants.lua
- src/gar.lua
- src/main.lua
- Corrected spelling of `expendited` -> `expedited` everywhere necessary
- Updated constant names from `FEE` to `RATE` where sensible
- Modified redundant unit test for instant delegate withdrawals to the max duration (non-invariant boundary case)
- Collected penalty rate and fee information for event data on instant withdrawals
> PE-6976: instant withdraw event data

- spec/gar_spec.lua
- src/gar.lua
- src/main.lua
Fixes for the following errors:
- Cancel-Delegate-Withdrawal: [string "aos"]:15425: attempt to index a nil value (field '?')
- Increase-Undername-Limit | [string "aos"]:14987: attempt to perform arithmetic on a nil value (field 'additionalUndernameCost')
- Increase-Undername-Limit | [string "aos"]:14247: attempt to index a nil value (local 'ioEvent')
- Extend-Lease | [string "aos"]:14926: attempt to perform arithmetic on a nil value (field 'totalExtensionFee')
> PE-7034: fix errors

- spec/epochs_spec.lua
- spec/gar_spec.lua
- src/balances.lua
- src/epochs.lua
- src/gar.lua
- src/utils.lua
- tests/tick.test.mjs
All delegates will have their rewards restaked against the rewarded gateway, rather than going to their balance. This is default behavior and cannot be overwritten
> fix(gar): autoStake all delegate rewards

- src/main.lua
- tests/arns.test.mjs
Adds 'Reassign-Name' which allows an ANT to configure a new process ID for its mapped ArNS name.
> Pe 6995 support ant reassignment for arns name

- spec/arns_spec.lua
- spec/setup.lua
- src/arns.lua
- src/demand.lua
- src/main.lua
- tests/arns.test.mjs
- tests/handlers.test.mjs
Allows `leased` names to be upgraded to a `permabuy` - can be performed by anyone and is just the cost of permabuying the name. There is no discount applied for the original leasing of the name.
> feat(PE-6996): allow upgrading leased names

- README.md
ran into a few hiccups during dev env setup. macOS brew install puts the include folder at `.../lua@5.3/include/lua5.3` rather than `.../lua@5.3/include`. In addition there are a few more installations needed for running the commands in the readme: `rust`, `luacov`, `aos`
> docs: add steps for dev on-boarding

- spec/arns_spec.lua
- src/arns.lua
- src/main.lua
- src/tick.lua
We can only discover records entering the grace period by looking for them on every message. Fortunately, pruning looks at every record during every message, so we can find them during that process. Additionally, once a record enters the grace period, we don't want to see it in event data again, so we'll keep a global record of the end timestamp of the last record end timestamp we saw in event data, and then will only add event data for records in the grace period in subsequent events if their end timestamp is after the largest last known end timestamp value.
> PE-7035: track discovery of records entering their grace period

- tools/evolve.mjs
accidently pushed to develop, verified this during that:
> chore: add git hash to evolve.mjs PE-6589

- spec/gar_spec.lua
- src/gar.lua
- src/main.lua
- src/utils.lua
- tests/gar.test.mjs
- tests/handlers.test.mjs
The handler returns a heterogenous, flattened list of active and vaulted delegations. Sorting can be done somewhat effectively by any fields that are common to both types of item. Here's an example list of items:
```
[
{
type: 'vault',
gatewayAddress: '2222222222222222222222222222222222222222222',
startTimestamp: 21600002,
delegationId:
'2222222222222222222222222222222222222222222_21600002',
balance: 400000001,
vaultId: 'decrease-stake-message-id',
endTimestamp: 2613600002,
},
{
type: 'stake',
gatewayAddress: '2222222222222222222222222222222222222222222',
delegationId:
'2222222222222222222222222222222222222222222_21600000',
balance: 599999999,
startTimestamp: 21600000,
},
{
type: 'stake',
gatewayAddress: 'second-gateway-aaaaaaaaaaaaaaaaaaaaaaaaaaaa',
delegationId: …
```
> PE-7093: delegations handler

- src/main.lua
- tests/tick.test.mjs
The CU throws out the memory on failure, so we can avoid copying state.
There is more I want to change here - right now prune runs on every message, but if it fails the next handler still gets called. Instead, we should bail out right away. That may mean not appending prune as a handler, but forcing it to be called on every message successfully before executing the handler logic related to the request.
> fix(prune): remove previous state handling in prune

- spec/arns_spec.lua
- src/arns.lua
- src/main.lua
- tests/arns.test.mjs
- tests/handlers.test.mjs
All large pieces of state should be returned as paginated arrays.
Need to validate e2e tests with SDK continue to work with current return types on these updated handlers.
> chore(main): remove handlers that are unbounded or old

- src/gar.lua
- src/main.lua
- src/token.lua
- tests/handlers.test.mjs
The token spec expects just the raw value for total supply, so separating it to a separate handler. Additionally, moves the computation to a function so we can add unit tests.
> fix(io): break out token supply handlers and use function to compute

- spec/epochs_spec.lua
- src/epochs.lua
- src/utils.lua
This one is a little different than the others because there's a very structured way in which the epochs are created and pruned. There's no need to reset the next prune timestamp after user actions here.
Note: I modified the deepCopy behavior to:
- do a very fast, basic deep copy if no exclusions are present
- if exclusions are present, activate the reindexing feature for numeric Arrays (not dictionaries)
> PE-7147: Prune Epochs Only When Necessary

- spec/primary_names_spec.lua
- src/primary_names.lua
- src/utils.lua
Allows a user to replace an existing primary name request with a new one, so long as it is a different name
> fix(primary): fix primary name request creation, replacing name for existing owner

- src/main.lua
supply is already adjusted within `addPrimaryNameRequestData`
> fix: only adjust supply once after primary name request PE-7298

- src/main.lua
- src/utils.lua
- tests/arns.test.mjs
- tests/gar.test.mjs
- tests/handlers.test.mjs
- tests/helpers.mjs
- tests/primary.test.mjs
- tests/tick.test.mjs
Adds `LastKnownMessageTimestamp` that is validated against the current message. Flagged some "invalid" states in our tests where timestamps were behind the latest. Additionally, it enforces input validation for all messages via a new `sanitize` handler. Note: we'll need to make sure this gets appended before `prune` on the `Handlers` object of the process.
> fix(main): add global handler to sanitize and validate inputs, enforce `LastKnownMessageTimestamp`

- src/main.lua
- tests/epochs.test.mjs
- tests/gar.test.mjs
- tests/tick.test.mjs
This avoids a breaking change that impacts the network portal and ar-io-sdk types
> fix(epochs): include prescribedObserversWithWeights to epoch handler

- tests/arns.test.mjs
- tests/helpers.mjs
- tests/invariants.mjs
- tests/primary.test.mjs
- tests/tick.test.mjs
- tests/transfer.test.mjs
- tests/vaults.test.mjs
After getting queasy with the reuse of sharedMemory in a few test files, I opted for the introduction of `endingMemory` in newly updated/integration tests.
> PE-7211: Check for invariants at conclusion of almost all integration tests

- .vscode/settings.json
- src/gar.lua
- src/main.lua
- tests/gar.test.mjs
Issues found:
- LastKnownWithdrawSupply being ADDED to rather than subtracted from
- LastKnownStakedSupply not being added to in the case where a delegation withdraw vault is used to redelegate to a new gateway
- (minor) incorrect types returned from gar.redelegateStake
> PE-7351: correctly account for moving stakes during redelegation 

- README.md
- spec/balances_spec.lua
- spec/epochs_spec.lua
- spec/gar_spec.lua
- src/ao_event.lua
- src/ario_event.lua
- src/arns.lua
- src/constants.lua
- src/epochs.lua
- src/gar.lua
- src/main.lua
- src/primary_names.lua
- src/utils.lua
- tests/handlers.test.mjs
- tests/monitor/monitor.test.mjs
- tests/primary.test.mjs
this PR addresses some of the TODOs. We still have 23 in the codebase, quite a few around improved testing coverage
- ~~removes timestamp conversion (looks good so far, test this devnet)~~ <-- did not blend, we need this converison
- gives types for ARIOEvent
- Adds Buy-Name handler in addition to Buy-Record in preparation for standardizing on `Name`
- excises TODOs that are already done or seemed unnecessary
> chore(cleanup): address TODOs PE-7339

- spec/gar_spec.lua
- src/ao_event.lua
- src/gar.lua
- src/main.lua
- src/tick.lua
- src/token.lua
New tallying info:
- Number of delegates that have a vault (distinct from total number of delegate vaults)
- Number of gateways that have a vault (distinct from total number of gateway vaults)
- Number of gateways that are exiting (now no longer part of the count of total gateways)
Also now collecting tallying info during prune gateways since that is the routine place where gateways objects are fully iterated through.
> PE-7281: collect more information in tallying workloads

- spec/gar_spec.lua
- src/gar.lua
- src/main.lua
- tests/gar.test.mjs
- tests/handlers.test.mjs
this PR adds a handler that returns paginated delegates from all gateways in the shape of 
```ts
{
address: string, // Address of the delegate
gatewayAddress: string, // Gateway address the stake is delegated to
delegatedStake: number, // Amount of stake currently delegated to gateway
startTimestamp: number, // Timestamp of when the delegate first staked to this gateway
vaultedStake: number, // Aggregation of all stake found in any vaults found for the delegate (stake being withdrawn)
},
```
> feat: add all paginated delegates to main handlers PE-7221

- package.json
- tests/monitor/monitor.test.mjs
- yarn.lock
These tests take ~10-15 mins to run in CI. That is too long. This leverages pLimit to concurrently execute tests, and moves some API calls up to avoid calling them multiple times across tests. There are more improvements we can make to run them concurrently (splitting into separate files), but this is sufficient for now.
These now run in 30-40 seconds on testnet.
```
ℹ tests 13
ℹ suites 9
ℹ pass 13
ℹ fail 0
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 35717.852429
✨  Done in 37.58s.
```
> chore(test): update monitor test, remove duplicate calls

- spec/vaults_spec.lua
- src/main.lua
- src/utils.lua
- src/vaults.lua
- tests/handlers.test.mjs
- tests/helpers.mjs
- tests/vaults.test.mjs
this PR:
- on vaulted-transfer: when in Tags: `{name: "Revokable": value: "true"}` -- add `controller` property to the vault populated with `msg.From` (signer of the message)
- adds new new revoke-vault handler
> PE-7514: revoked vaults

- spec/epochs_spec.lua
- src/epochs.lua
- tests/epochs.test.mjs
Now that we post epoch distributions we no longer need to store them in state. This should give us material memory savings, but we will validate using lua memory collector in devnet before we cleanup other functions related to pruning.
> chore(epochs): remove old epochs

- spec/arns_spec.lua
- src/arns.lua
- src/constants.lua
- src/epochs.lua
- src/gar.lua
- src/primary_names.lua
- src/vaults.lua
- tests/helpers.mjs
- tests/prune.test.mjs
This bug delays the pruning of records that should be removed after their grace period ends. 
TLDR:
- we correctly remove records that are expired
- we correctly update the minimum `NextRecordsPruneTimestamp` for those in their grace period
- we use `minEndTimestamp` to track the lowest endTimestamp of all records that are NOT in their grace period or expired
- we INCORRECTLY `nil` out `NextRecordsPruneTimestamp` and then set it to the `minNextEndTimestamp` variable if it was set, **overwriting any minimum that should have been set by records in their grace period**
Here is the `pruneRecords` function with additional comments (IN CAPS) on where/why the bug occurs
```lua
--- Prunes records that have expired
--- @param currentTimestamp number The current timestamp
--- @param …
```
> chore(PE-7555): fix arns pruning bug, standardize logic for pruning

- spec/epochs_spec.lua
- spec/gar_spec.lua
- src/epochs.lua
- src/gar.lua
- src/main.lua
- tests/epochs.test.mjs
- tests/gar.test.mjs
- tests/handlers.test.mjs
- tests/tick.test.mjs
SDK and Network-portal are updated to use the new values. We can stop storing them on the contract
> chore(PE-7040): remove deprecated gateway attributes

- spec/arns_spec.lua
- spec/epochs_spec.lua
- spec/primary_names_spec.lua
- src/arns.lua
- src/epochs.lua
These stats are computed at the beginning of an epoch, and just used for historical tracking. Every epoch has a start and timestamp - and these stats are computed at the beginning on an epoch.
- Active names: at the beginning of an epoch, these names are ACTIVE
- Reserved names: at the beginnog of an epoch, these names are RESERVED
- Returned names: at the beginning of an epoch these names are RETURNED
- Grace period names: at the beginning of an epoch, these names are in their GRACE PERIOD
> fix(arns): fix arns stat issue

- spec/arns_spec.lua
- spec/gar_spec.lua
- src/arns.lua
- src/constants.lua
- src/demand.lua
- src/epochs.lua
- src/gar.lua
- src/primary_names.lua
100% fo the minimum operator stake will be slashed when a gateway is forced to leave.
Also - updates our constants and time conversions to all use utilities. Avoided putting in `utils` due to potential recursive dependency.
> fix(gar): update slash rate to 1, standardize time conversions
