.busted
.github/workflows/build.yaml
.gitignore
.luacov
spec/epochs_spec.lua
src/demand.lua

Lowers demandFactorDownAdjustment to 1.5% from 2.5%.

chore: update demandFactorDownAdjustment

---

spec/arns_spec.lua
spec/gar_spec.lua
spec/vaults_spec.lua
src/arns.lua
src/constants.lua
src/epochs.lua
src/gar.lua
src/main.lua
src/tick.lua
src/vaults.lua
tests/gar.test.mjs
tests/tick.test.mjs
tests/vaults.test.mjs
tools/constants.mjs

chore: devnet to testnet

---

src/demand.lua

Includes demand factor fixes for moving average array

chore: testnet to devnet

---

spec/arns_spec.lua
spec/utils_spec.lua
src/arns.lua
src/gar.lua
src/io_event.lua
src/main.lua
src/tick.lua
src/utils.lua

Instrumentation for:
- Buy-Record
- Extend-Lease
- Increase-Undername-Limit
- Record pruned (name expired)

PE-6795: Instrument record-related events

---

spec/arns_spec.lua
spec/gar_spec.lua
spec/utils_spec.lua
src/ao_event.lua
src/arns.lua
src/gar.lua
src/io_event.lua
src/main.lua
src/tick.lua
src/utils.lua
src/vaults.lua
tests/gar.test.mjs

Added tracking events for:
- Transfer
- Create-Vault
- Delegate-Stake
- Decrease-Delegate-Stake
- Cancel-Delegate-Withdrawl
- "Extend-Vault"
- "Increase-Vault"
Added function `eventingPcall` that DRYs out sending errors along with events when pcalls fail.

PE-6794: IO Usage Events

---

src/demand.lua
src/epochs.lua
src/main.lua
src/tick.lua

Important fix there for tracking pruned records as well.

feat(events): instrument epoch ticking and demand factor updates PE-6797

---

src/gar.lua
src/main.lua
tests/monitor/monitor.test.mjs

This caused the protocol balance to get slashes rewards multiple times when ticking should have failed and reverted the balances

fix(gar): make sure we revert balances on pruning if failure, update monitor tests

---

spec/arns_spec.lua
src/arns.lua
src/main.lua
src/tick.lua
tests/arns.test.mjs
tests/tick.test.mjs
tools/constants.mjs

Instead of pruning records, the names will go into auction with the rewards all given to the protocol balance

feat(auctions): introduce lease expiration initiated auctions

---

.luarc.json
package.json
src/main.lua
tests/arns.test.mjs
tests/gar.test.mjs
tests/monitor/monitor.test.mjs

Validating the behavior of paginated gateways

chore(test): add paginated gateway test

---

spec/arns_spec.lua
spec/gar_spec.lua
src/arns.lua
src/gar.lua
src/main.lua
tests/arns.test.mjs
tests/helpers.mjs

- Reorder algorithm for funding drawdowns to put withdraw stakes ahead of excess active stakes
- Allow for auction bidding from multiple funding sources

PE-7103: use withdraw vaults before excess stakes AND auction bid from multiple funding sources

---

src/arns.lua

Some type updates and memory efficiency.

feat(gar): repair some types

---

spec/demand_spec.lua
spec/epochs_spec.lua
src/demand.lua
src/epochs.lua
src/gar.lua

These functions are never directly used in any of our source code.

chore(lua): remove unused functions

---

spec/gar_spec.lua
src/demand.lua
src/epochs.lua
src/gar.lua
src/main.lua
src/tick.lua
src/utils.lua
tests/tick.test.mjs

We will add unit tests to make sure this happens correctly

fix(tick): move tickEpoch to separate function

---

src/arns.lua

when not providing Years on Token-Cost of type 'lease' we see `]:6860: attempt to perform arithmetic on a nil value (local 'years')`:
```sh
{"level":"debug","message":"Evaluating read interaction on contract","name":"ar-io-sdk","tags":[{"name":"Action","value":"Token-Cost"},{"name":"Intent","value":"Buy-Record"},{"name":"Name","value":"my-name"},{"name":"Timestamp","value":"1732562026000"}],"timestamp":"2024-11-25T19:19:02.641Z","version":"2.5.0-alpha.13"}
{"level":"debug","message":"Read interaction result","name":"ar-io-sdk","result":{"Assignments":[],"GasUsed":2691395618,"Messages":[{"Anchor":"00000000000000000000000000002902","Data":"[string \"aos\"]:6860: attempt to perform arithmetic on a nil value (local 'years')","Tags":[{"name":"Data-Protocol","value":"ao"},{"name":"Variant","valu …
```

fix: assert required years on lease token cost

---

spec/gar_spec.lua
src/gar.lua
tests/gar.test.mjs
tests/helpers.mjs
tests/tick.test.mjs
tools/constants.mjs

Moves the gar functions to helpers.mjs, and updates tests with new values
Includes PE-7186/PE-7187/PE-7188

fix(gar): update gar settings, minimum stakes, withdrawal lengths

---

src/balances.lua
src/main.lua
src/token.lua

I initially added tallying in pruneGateways but it's difficult to test tallying there. This is a quick start that allows us to get the data on demand.

feat(tallies): add tallies for major state objects PE-7281

---

src/main.lua

This PR removes `LastTickedEpochIndex` with more graunlar globals `LastCreatedEpochIndex` and `LastDistributedEpochIndex`

fix(tick): update the globals for tick

---

spec/arns_spec.lua
src/arns.lua
tests/arns.test.mjs

These are flat rates depending on the demand factor and undername percentage fee. This aligns the process with the whitepaper.

fix(arns): remove years on cost of undernames

---

spec/epochs_spec.lua
src/arns.lua
src/epochs.lua
tests/epochs.test.mjs
tests/tick.test.mjs

Adds new API to created and distributed Epochs 
```ts
/** epoch.arnsStats */
export type ArnsStats = {
totalActiveNames: number;
totalGracePeriodNames: number;
totalReservedNames: number;
totalReturnedNames: number;
}
```

feat(arns stats): add arns stats to created and distributed epochs PE-7415

---

.github/workflows/build.yaml

V4 includes the updated tests and types

chore(sdk): use v4.0.0 of the SDK

---

spec/vaults_spec.lua
src/vaults.lua
tests/helpers.mjs
tests/vaults.test.mjs

Use unsafe and add remove vault helper

chore(vaults): update pruning logic for vaults

---

patches/2025-04-29-check-nil-transfer.lua
src/main.lua
tests/transfer.test.mjs

This throws up as expected, but the error is not friendly. Adds a check that quantity is provided, before validating the value. Also adds a few more integration tests

fix(ario): validate qty is provided on transfer
